-- Seed device_models เฉพาะรุ่นที่ขายจริงในตลาดไทย (2020-2026) ของ 7 แบรนด์หลัก:
-- Apple, Samsung, Xiaomi/Redmi, OPPO, vivo, realme, Huawei/Honor
-- ค้นคว้าอ้างอิงจาก siamphone.com + เว็บข่าวไอทีไทย ต่อเนื่องจาก 2 migration seed เดิม (idempotent, ไม่ซ้ำ ไม่ลบของเดิม)
insert into public.device_models (model_name)
values
  ('iPhone SE (2020)'),
  ('iPhone SE (2022)'),
  ('iPhone 17'),
  ('iPhone 17 Pro'),
  ('iPhone 17 Pro Max'),
  ('iPhone Air'),
  ('iPhone 17e'),
  ('Samsung Galaxy S20'),
  ('Samsung Galaxy S20+'),
  ('Samsung Galaxy S20 Ultra'),
  ('Samsung Galaxy S20 FE'),
  ('Samsung Galaxy Note 20'),
  ('Samsung Galaxy Note 20 Ultra'),
  ('Samsung Galaxy Z Flip'),
  ('Samsung Galaxy Z Flip 5G'),
  ('Samsung Galaxy Z Fold2'),
  ('Samsung Galaxy A01'),
  ('Samsung Galaxy A01 Core'),
  ('Samsung Galaxy A11'),
  ('Samsung Galaxy A21'),
  ('Samsung Galaxy A21s'),
  ('Samsung Galaxy A31'),
  ('Samsung Galaxy A41'),
  ('Samsung Galaxy A51'),
  ('Samsung Galaxy A51 5G'),
  ('Samsung Galaxy A71'),
  ('Samsung Galaxy A71 5G'),
  ('Samsung Galaxy M11'),
  ('Samsung Galaxy M21'),
  ('Samsung Galaxy M31'),
  ('Samsung Galaxy M51'),
  ('Samsung Galaxy M01'),
  ('Samsung Galaxy A03'),
  ('Samsung Galaxy A03s'),
  ('Samsung Galaxy A12 Nacho'),
  ('Samsung Galaxy A22'),
  ('Samsung Galaxy A22 5G'),
  ('Samsung Galaxy A32'),
  ('Samsung Galaxy A32 5G'),
  ('Samsung Galaxy A52'),
  ('Samsung Galaxy A52 5G'),
  ('Samsung Galaxy A52s 5G'),
  ('Samsung Galaxy A72'),
  ('Samsung Galaxy M02'),
  ('Samsung Galaxy M02s'),
  ('Samsung Galaxy M12'),
  ('Samsung Galaxy M22'),
  ('Samsung Galaxy M32'),
  ('Samsung Galaxy M32 5G'),
  ('Samsung Galaxy M42'),
  ('Samsung Galaxy M52 5G'),
  ('Samsung Galaxy M62'),
  ('Samsung Galaxy S21'),
  ('Samsung Galaxy S21+'),
  ('Samsung Galaxy S21 Ultra'),
  ('Samsung Galaxy XCover 5'),
  ('Samsung Galaxy XCover Pro'),
  ('Samsung Galaxy Z Fold3'),
  ('Samsung Galaxy Z Flip3'),
  ('Samsung Galaxy A04'),
  ('Samsung Galaxy A04e'),
  ('Samsung Galaxy A04s'),
  ('Samsung Galaxy A13'),
  ('Samsung Galaxy A13 5G'),
  ('Samsung Galaxy A23'),
  ('Samsung Galaxy A23 5G'),
  ('Samsung Galaxy A33 5G'),
  ('Samsung Galaxy A53 5G'),
  ('Samsung Galaxy A73 5G'),
  ('Samsung Galaxy M04'),
  ('Samsung Galaxy M13'),
  ('Samsung Galaxy M13 5G'),
  ('Samsung Galaxy M23'),
  ('Samsung Galaxy M33'),
  ('Samsung Galaxy M53'),
  ('Samsung Galaxy S21 FE 5G'),
  ('Samsung Galaxy S22'),
  ('Samsung Galaxy S22+'),
  ('Samsung Galaxy S22 Ultra'),
  ('Samsung Galaxy XCover6 Pro'),
  ('Samsung Galaxy Z Fold4'),
  ('Samsung Galaxy Z Flip4'),
  ('Samsung Galaxy A05'),
  ('Samsung Galaxy A05s'),
  ('Samsung Galaxy A14'),
  ('Samsung Galaxy A14 5G'),
  ('Samsung Galaxy A24 4G'),
  ('Samsung Galaxy A34'),
  ('Samsung Galaxy A54'),
  ('Samsung Galaxy M14 5G'),
  ('Samsung Galaxy M34 5G'),
  ('Samsung Galaxy M54'),
  ('Samsung Galaxy S23'),
  ('Samsung Galaxy S23+'),
  ('Samsung Galaxy S23 Ultra'),
  ('Samsung Galaxy S23 FE'),
  ('Samsung Galaxy Z Fold5'),
  ('Samsung Galaxy Z Flip5'),
  ('Samsung Galaxy A06'),
  ('Samsung Galaxy A15'),
  ('Samsung Galaxy A15 5G'),
  ('Samsung Galaxy A16 5G'),
  ('Samsung Galaxy A25'),
  ('Samsung Galaxy A35 5G'),
  ('Samsung Galaxy A55'),
  ('Samsung Galaxy M05'),
  ('Samsung Galaxy M14 4G'),
  ('Samsung Galaxy M15'),
  ('Samsung Galaxy M55'),
  ('Samsung Galaxy S24'),
  ('Samsung Galaxy S24+'),
  ('Samsung Galaxy S24 Ultra'),
  ('Samsung Galaxy S24 FE'),
  ('Samsung Galaxy Z Fold6'),
  ('Samsung Galaxy Z Flip6'),
  ('Samsung Galaxy A06 5G'),
  ('Samsung Galaxy A07'),
  ('Samsung Galaxy A16'),
  ('Samsung Galaxy A17'),
  ('Samsung Galaxy A17 4G'),
  ('Samsung Galaxy A26'),
  ('Samsung Galaxy A36'),
  ('Samsung Galaxy A56'),
  ('Samsung Galaxy M07'),
  ('Samsung Galaxy M17'),
  ('Samsung Galaxy M56'),
  ('Samsung Galaxy S25'),
  ('Samsung Galaxy S25+'),
  ('Samsung Galaxy S25 Ultra'),
  ('Samsung Galaxy S25 Edge'),
  ('Samsung Galaxy S25 FE'),
  ('Samsung Galaxy XCover 7'),
  ('Samsung Galaxy XCover 7 Pro'),
  ('Samsung Galaxy Z Fold7'),
  ('Samsung Galaxy Z Flip7'),
  ('Samsung Galaxy Z Flip7 FE'),
  ('Samsung Galaxy Z TriFold'),
  ('Samsung Galaxy A07 5G'),
  ('Samsung Galaxy A37 5G'),
  ('Samsung Galaxy A57 5G'),
  ('Samsung Galaxy M17e'),
  ('Samsung Galaxy S26'),
  ('Samsung Galaxy S26+'),
  ('Samsung Galaxy S26 Ultra'),
  ('Samsung Galaxy Z Fold8'),
  ('Samsung Galaxy Z Fold8 Ultra'),
  ('Samsung Galaxy Z Flip8'),
  ('Samsung Galaxy A27 5G'),
  ('Xiaomi Mi 10 Pro 5G'),
  ('Xiaomi Mi 10 Lite'),
  ('Xiaomi Mi 10 Youth Edition'),
  ('Xiaomi Mi Note 10 Lite'),
  ('Xiaomi Mi 10T'),
  ('Xiaomi Mi 10T Pro'),
  ('Xiaomi Mi 10T Lite'),
  ('Xiaomi Mi 10 Ultra'),
  ('Xiaomi Mi 11 Lite'),
  ('Xiaomi Mi 11 Lite 5G'),
  ('Xiaomi Mi 11 Pro'),
  ('Xiaomi Mi 11 Ultra'),
  ('Xiaomi Mi 11 Special Edition'),
  ('Xiaomi 11T Pro'),
  ('Xiaomi 11 Lite 5G NE'),
  ('Xiaomi 12 Pro'),
  ('Xiaomi 12 Lite 5G'),
  ('Xiaomi 12T Pro'),
  ('Xiaomi 13 Pro'),
  ('Xiaomi 13 Lite'),
  ('Xiaomi 13T Pro'),
  ('Xiaomi 14 Ultra'),
  ('Xiaomi 14T Pro'),
  ('Xiaomi Mix Flip'),
  ('Xiaomi 15'),
  ('Xiaomi 15 Ultra'),
  ('Xiaomi 15 Pro'),
  ('Xiaomi 15T'),
  ('Xiaomi 15T Pro'),
  ('Xiaomi Mix Flip 2'),
  ('Xiaomi 17'),
  ('Xiaomi 17 Pro'),
  ('Xiaomi 17 Pro Max'),
  ('Xiaomi 17T'),
  ('Xiaomi 17T Pro'),
  ('Xiaomi 17 Ultra'),
  ('Redmi 9 Power'),
  ('Redmi Note 9 4G'),
  ('Redmi Note 9 Pro 5G'),
  ('Redmi Note 9s'),
  ('Redmi 9T'),
  ('Redmi Note 9T 5G'),
  ('Redmi Note 10 5G'),
  ('Redmi Note 10S'),
  ('Redmi Note 10 Pro Max'),
  ('Redmi 10 Prime'),
  ('Redmi Note 11 4G'),
  ('Redmi Note 11S'),
  ('Redmi Note 11 Pro 5G'),
  ('Redmi Note 11 Pro Plus'),
  ('Redmi Note 11 SE'),
  ('Redmi Note 11T Pro'),
  ('Redmi Note 11T Pro Plus'),
  ('Redmi Note 11E'),
  ('Redmi Note 11E Pro'),
  ('Redmi 10 5G'),
  ('Redmi A1'),
  ('Redmi Note 12 4G'),
  ('Redmi Note 12 5G'),
  ('Redmi Note 12S'),
  ('Redmi Note 12 Pro Plus'),
  ('Redmi Note 12 Pro 4G'),
  ('Redmi Note 12 Turbo'),
  ('Redmi 12 5G'),
  ('Redmi A2'),
  ('Redmi A2 Plus'),
  ('Redmi Note 13 4G'),
  ('Redmi Note 13 Pro Plus'),
  ('Redmi Note 13 Pro 4G'),
  ('Redmi Note 13R'),
  ('Redmi 13 5G'),
  ('Redmi 13C 5G'),
  ('Redmi A3'),
  ('Redmi Turbo 3'),
  ('Redmi K70 Ultra'),
  ('Redmi Note 14'),
  ('Redmi Note 14 Pro'),
  ('Redmi Note 14 Pro Plus'),
  ('Redmi 14C'),
  ('Redmi A5 4G'),
  ('Redmi Turbo 4'),
  ('Redmi Turbo 4 Pro'),
  ('Redmi 15'),
  ('Redmi 15 5G'),
  ('Redmi 13x'),
  ('Redmi Note 15'),
  ('Redmi Note 15 Pro'),
  ('Redmi Note 15 Pro Plus'),
  ('Redmi 15C'),
  ('Redmi A7 Pro'),
  ('Redmi Turbo 5'),
  ('Redmi K90'),
  ('Redmi K90 Pro Max'),
  ('OPPO A73 (2020)'),
  ('OPPO A72'),
  ('OPPO A12s'),
  ('OPPO A92s'),
  ('OPPO A31 (2020)'),
  ('OPPO Reno 3 Pro'),
  ('OPPO F17'),
  ('OPPO F17 Pro'),
  ('OPPO Reno 4'),
  ('OPPO Reno 4 Pro'),
  ('OPPO Reno 4 Z'),
  ('OPPO Reno 4 Lite'),
  ('OPPO Reno 4 SE'),
  ('OPPO Find X2'),
  ('OPPO Find X2 Pro'),
  ('OPPO Find X2 Lite'),
  ('OPPO A56 5G'),
  ('OPPO A55 4G'),
  ('OPPO A35'),
  ('OPPO A74 4G'),
  ('OPPO A74 5G'),
  ('OPPO A93 5G'),
  ('OPPO A93s 5G'),
  ('OPPO A94'),
  ('OPPO A94 5G'),
  ('OPPO Reno 5'),
  ('OPPO Reno 5 5G'),
  ('OPPO Reno 5 Pro'),
  ('OPPO Reno 5 Pro Plus'),
  ('OPPO Reno 5Z'),
  ('OPPO Reno 5F'),
  ('OPPO Reno 5K 5G'),
  ('OPPO Reno 6'),
  ('OPPO Reno 6 Pro'),
  ('OPPO Reno 6 Pro Plus'),
  ('OPPO Reno 6Z 5G'),
  ('OPPO Find X3'),
  ('OPPO Find X3 Pro'),
  ('OPPO Find X3 Lite'),
  ('OPPO Find X3 Neo'),
  ('OPPO F19'),
  ('OPPO F19 Pro'),
  ('OPPO F19 Pro Plus'),
  ('OPPO K9 5G'),
  ('OPPO K9 Pro'),
  ('OPPO A11s'),
  ('OPPO A36'),
  ('OPPO A55 5G'),
  ('OPPO A57 (2022)'),
  ('OPPO A57 5G'),
  ('OPPO A77 4G'),
  ('OPPO A77 5G'),
  ('OPPO A77s'),
  ('OPPO A96 5G'),
  ('OPPO A97 5G'),
  ('OPPO A17k'),
  ('OPPO Find X5 Pro'),
  ('OPPO Find X5 Lite'),
  ('OPPO Find N2'),
  ('OPPO Find N2 Flip'),
  ('OPPO Reno7 5G'),
  ('OPPO Reno7 Pro 5G'),
  ('OPPO Reno7 Z 5G'),
  ('OPPO Reno8 Z 5G'),
  ('OPPO Reno8 Pro'),
  ('OPPO Reno8 Pro Plus'),
  ('OPPO Reno9 Pro'),
  ('OPPO Reno9 Pro Plus'),
  ('OPPO K10'),
  ('OPPO K10 5G'),
  ('OPPO K10 Pro 5G'),
  ('OPPO A38'),
  ('OPPO A78 5G'),
  ('OPPO A79 5G'),
  ('OPPO A98 5G'),
  ('OPPO A2'),
  ('OPPO A2x'),
  ('OPPO A2 Pro'),
  ('OPPO Find X6 Pro'),
  ('OPPO Find N3'),
  ('OPPO Find N3 Flip'),
  ('OPPO Reno8 T'),
  ('OPPO Reno8 T 5G'),
  ('OPPO Reno10 Pro'),
  ('OPPO Reno10 Pro Plus 5G'),
  ('OPPO A60'),
  ('OPPO A80'),
  ('OPPO A59 5G'),
  ('OPPO A3 Pro 5G'),
  ('OPPO A3x'),
  ('OPPO Reno11 Pro'),
  ('OPPO Reno11 F 5G'),
  ('OPPO Find X7 Ultra'),
  ('OPPO Find X8'),
  ('OPPO Find X8 Pro'),
  ('OPPO K13 Turbo'),
  ('OPPO K13 Turbo Pro'),
  ('OPPO K13x'),
  ('OPPO A5 Pro'),
  ('OPPO A5 Pro 4G'),
  ('OPPO A5 4G'),
  ('OPPO A5x'),
  ('OPPO A5i'),
  ('OPPO A6'),
  ('OPPO A6 5G'),
  ('OPPO A6 Pro'),
  ('OPPO A6 Pro 5G'),
  ('OPPO A6x'),
  ('OPPO A6x 5G'),
  ('OPPO Reno13'),
  ('OPPO Reno13 Pro'),
  ('OPPO Reno13 F'),
  ('OPPO Reno14'),
  ('OPPO Reno14 Pro'),
  ('OPPO Reno14 F 5G'),
  ('OPPO Find N5'),
  ('OPPO Find X8s'),
  ('OPPO Find X8s Plus'),
  ('OPPO Find X8 Ultra'),
  ('OPPO Find X9'),
  ('OPPO Find X9 Pro'),
  ('OPPO A6s'),
  ('OPPO A6c'),
  ('OPPO A6t Pro'),
  ('OPPO Find X9 Ultra'),
  ('OPPO Find X9s'),
  ('OPPO Find N6'),
  ('OPPO K15 Pro'),
  ('OPPO K15 Pro Plus'),
  ('OPPO Reno15'),
  ('OPPO Reno15 Pro'),
  ('OPPO Reno15 Pro Max'),
  ('OPPO Reno15 F'),
  ('OPPO Reno16 5G'),
  ('OPPO Reno16 Pro 5G'),
  ('OPPO Reno16 F 5G'),
  ('vivo V19'),
  ('vivo V19 Neo'),
  ('vivo Y30'),
  ('vivo Y50'),
  ('vivo Y70s'),
  ('vivo Y91C'),
  ('vivo S1 Prime'),
  ('vivo Y20'),
  ('vivo Y20i'),
  ('vivo Y20s'),
  ('vivo Y1s'),
  ('vivo Y51'),
  ('vivo Y51s'),
  ('vivo Y52s'),
  ('vivo Y73s'),
  ('vivo V20'),
  ('vivo V20 SE'),
  ('vivo V20 Pro'),
  ('vivo X50'),
  ('vivo X50 Pro'),
  ('vivo X50 Pro Plus'),
  ('vivo X50e'),
  ('vivo X60'),
  ('vivo S7'),
  ('vivo S7e'),
  ('vivo S6'),
  ('vivo Z6'),
  ('vivo NEX 3S'),
  ('vivo V21'),
  ('vivo V21e'),
  ('vivo V23 5G'),
  ('vivo V23e'),
  ('vivo Y12s'),
  ('vivo Y12A'),
  ('vivo Y12G'),
  ('vivo Y20G'),
  ('vivo Y20T'),
  ('vivo Y20s G'),
  ('vivo Y21'),
  ('vivo Y21A'),
  ('vivo Y21T'),
  ('vivo Y21e'),
  ('vivo Y31'),
  ('vivo Y31s'),
  ('vivo Y33s'),
  ('vivo Y52 5G'),
  ('vivo Y53s'),
  ('vivo Y53s 4G'),
  ('vivo Y70t'),
  ('vivo Y72 5G'),
  ('vivo Y74s'),
  ('vivo Y75'),
  ('vivo Y75 5G'),
  ('vivo Y75s 5G'),
  ('vivo Y76 5G'),
  ('vivo Y76s'),
  ('vivo S9'),
  ('vivo S10'),
  ('vivo S10 Pro'),
  ('vivo X60 Pro'),
  ('vivo X60 Pro Plus'),
  ('vivo X60t'),
  ('vivo X60t Pro Plus'),
  ('vivo X70'),
  ('vivo X70 Pro'),
  ('vivo X70 Pro Plus'),
  ('vivo V25 5G'),
  ('vivo V25 Pro 5G'),
  ('vivo Y02'),
  ('vivo Y02s'),
  ('vivo Y16'),
  ('vivo Y22'),
  ('vivo Y22s'),
  ('vivo Y30 5G'),
  ('vivo Y33T'),
  ('vivo Y35'),
  ('vivo Y35 5G'),
  ('vivo Y52t'),
  ('vivo Y55'),
  ('vivo Y55 5G'),
  ('vivo Y72t'),
  ('vivo Y73t'),
  ('vivo Y75s'),
  ('vivo Y77'),
  ('vivo Y77e'),
  ('vivo T1 5G'),
  ('vivo T1x 4G'),
  ('vivo T2'),
  ('vivo T2x'),
  ('vivo S15'),
  ('vivo S15 Pro'),
  ('vivo S15e'),
  ('vivo X80'),
  ('vivo X80 Pro'),
  ('vivo X80 Lite'),
  ('vivo X Fold'),
  ('vivo X Fold Plus'),
  ('vivo X Note'),
  ('vivo Y01'),
  ('vivo Y11'),
  ('vivo Y27'),
  ('vivo Y27 5G'),
  ('vivo Y27s'),
  ('vivo Y36'),
  ('vivo Y36 5G'),
  ('vivo Y56'),
  ('vivo Y77t'),
  ('vivo Y78t'),
  ('vivo Y100 4G'),
  ('vivo Y100i'),
  ('vivo S16'),
  ('vivo S16 Pro'),
  ('vivo S16e'),
  ('vivo V27'),
  ('vivo V27e'),
  ('vivo V27 Pro'),
  ('vivo V29'),
  ('vivo V29 5G'),
  ('vivo V29e'),
  ('vivo V29 Pro'),
  ('vivo X90'),
  ('vivo X90 Pro'),
  ('vivo X Fold2'),
  ('vivo T2 Pro'),
  ('vivo Y17s'),
  ('vivo Y18'),
  ('vivo Y18t'),
  ('vivo Y28'),
  ('vivo Y28s'),
  ('vivo Y36i'),
  ('vivo Y38'),
  ('vivo Y100'),
  ('vivo Y19s'),
  ('vivo Y19s Pro'),
  ('vivo Y200'),
  ('vivo Y200i'),
  ('vivo Y200 4G'),
  ('vivo Y200 Plus'),
  ('vivo Y03'),
  ('vivo Y03t'),
  ('vivo T3'),
  ('vivo V30'),
  ('vivo V30 Pro'),
  ('vivo V30 SE'),
  ('vivo V30 Lite'),
  ('vivo V30 Lite 4G'),
  ('vivo V40'),
  ('vivo V40 Pro'),
  ('vivo V40 SE'),
  ('vivo V40e'),
  ('vivo X100'),
  ('vivo X100 Pro'),
  ('vivo X Fold3'),
  ('vivo X Fold3 Pro'),
  ('vivo S18'),
  ('vivo S18 Pro'),
  ('vivo S18e'),
  ('vivo Y04'),
  ('vivo Y29 4G'),
  ('vivo Y39'),
  ('vivo Y18e'),
  ('vivo Y21d'),
  ('vivo V50'),
  ('vivo V50 Lite'),
  ('vivo V60'),
  ('vivo V60 Lite'),
  ('vivo X200'),
  ('vivo X200 Pro'),
  ('vivo X200 Pro mini'),
  ('vivo X200 FE'),
  ('vivo X Fold5'),
  ('vivo Y300 GT'),
  ('vivo Y04s'),
  ('vivo Y05'),
  ('vivo Y11d'),
  ('vivo Y31 5G'),
  ('vivo Y31d'),
  ('vivo S50'),
  ('vivo S50 Pro mini'),
  ('vivo V70'),
  ('vivo X300'),
  ('vivo X300 Pro'),
  ('vivo X300 FE'),
  ('realme 5'),
  ('realme 5i'),
  ('realme 5s'),
  ('realme 5 Pro'),
  ('realme 3 Pro'),
  ('realme C2'),
  ('realme C3'),
  ('realme 6'),
  ('realme 6i'),
  ('realme 6 Pro'),
  ('realme 6s'),
  ('realme X3'),
  ('realme X3 SuperZoom'),
  ('realme X50 Pro'),
  ('realme 7'),
  ('realme 7i'),
  ('realme 7 Pro'),
  ('realme C15'),
  ('realme C11'),
  ('realme C12'),
  ('realme C17'),
  ('realme Narzo 10A'),
  ('realme Narzo 20'),
  ('realme Narzo 20 Pro'),
  ('realme Narzo 20A'),
  ('realme 8'),
  ('realme 8 Pro'),
  ('realme C21'),
  ('realme C25'),
  ('realme C20'),
  ('realme Narzo 30'),
  ('realme Narzo 30 Pro'),
  ('realme Narzo 30A'),
  ('realme 8s 5G'),
  ('realme 8i'),
  ('realme GT'),
  ('realme GT Master'),
  ('realme GT Master Explorer'),
  ('realme C25s'),
  ('realme C25Y'),
  ('realme 9'),
  ('realme 9 Pro'),
  ('realme 9 Pro Plus'),
  ('realme 9i'),
  ('realme C35'),
  ('realme C31'),
  ('realme C21Y'),
  ('realme Narzo 50'),
  ('realme Narzo 50A'),
  ('realme Narzo 50A Prime'),
  ('realme Narzo 50 Pro 5G'),
  ('realme Narzo 50i'),
  ('realme Narzo 50i Prime'),
  ('realme Narzo 50 5G'),
  ('realme 9 5G'),
  ('realme GT 2'),
  ('realme GT 2 Pro'),
  ('realme GT Neo 2T'),
  ('realme GT Neo 3'),
  ('realme GT Neo 3T'),
  ('realme C33'),
  ('realme C30'),
  ('realme C30s'),
  ('realme 10'),
  ('realme 10 Pro'),
  ('realme 10 Pro Plus'),
  ('realme 10S'),
  ('realme 11'),
  ('realme 11 4G'),
  ('realme 11 5G'),
  ('realme 11 Pro 5G'),
  ('realme 11 Pro Plus 5G'),
  ('realme C51'),
  ('realme C53'),
  ('realme C55'),
  ('realme C67'),
  ('realme C67 4G'),
  ('realme GT Neo 5'),
  ('realme GT Neo 5 SE'),
  ('realme GT 5'),
  ('realme GT 5 Pro'),
  ('realme Narzo N53'),
  ('realme 12'),
  ('realme 12x'),
  ('realme 12 Pro'),
  ('realme 12 Pro Plus'),
  ('realme 12 Plus 5G'),
  ('realme C63'),
  ('realme C65'),
  ('realme C65 5G'),
  ('realme C61'),
  ('realme C75'),
  ('realme Narzo 70'),
  ('realme Narzo 70 Pro'),
  ('realme Narzo 70x'),
  ('realme 13'),
  ('realme 13 Plus'),
  ('realme GT 6'),
  ('realme GT 6T'),
  ('realme GT Neo 6'),
  ('realme Note 50'),
  ('realme Note 60'),
  ('realme Note 60x'),
  ('realme 14'),
  ('realme 14x'),
  ('realme 14 Pro'),
  ('realme 14 Pro Plus'),
  ('realme 14T'),
  ('realme C71'),
  ('realme C85'),
  ('realme Narzo 80 Pro'),
  ('realme Neo 7'),
  ('realme Neo 7 SE'),
  ('realme P3 Pro'),
  ('realme P3x'),
  ('realme GT 7'),
  ('realme GT 7 Pro'),
  ('realme GT 7T'),
  ('realme 15'),
  ('realme 15T'),
  ('realme 15 Pro'),
  ('realme Note 70'),
  ('realme 16'),
  ('realme 16 Pro'),
  ('realme 16 Pro Plus'),
  ('realme P4 Power 5G'),
  ('realme Note 80'),
  ('realme C100 5G'),
  ('realme C100i'),
  ('realme C100x'),
  ('Huawei P40 Pro Plus'),
  ('Huawei P40 lite'),
  ('Huawei P Smart S'),
  ('Huawei P smart 2021'),
  ('Huawei Mate 40 Pro'),
  ('Huawei Mate 40 Pro Plus'),
  ('Huawei Mate 40 RS Porsche Design'),
  ('Huawei Mate Xs'),
  ('Huawei nova 7'),
  ('Huawei nova 7 Pro'),
  ('Huawei nova 7i'),
  ('Huawei nova 7 SE'),
  ('Huawei nova 8'),
  ('Huawei nova 8 Pro'),
  ('Huawei nova 8 SE'),
  ('Huawei Y5p'),
  ('Huawei Y6p'),
  ('Huawei Y7a'),
  ('Huawei Y7p'),
  ('Huawei Y8p'),
  ('Huawei Y8s'),
  ('Huawei Y9a'),
  ('Huawei Mate X2'),
  ('Huawei Mate 40E 5G'),
  ('Huawei nova 8 Pro 4G'),
  ('Huawei nova 8i'),
  ('Huawei nova 8 SE 4G'),
  ('Huawei nova 9'),
  ('Huawei nova 9 Pro'),
  ('Huawei P50'),
  ('Huawei P50 Pro'),
  ('Huawei P50 Pocket'),
  ('Huawei Mate Xs 2'),
  ('Huawei nova Y60'),
  ('Huawei nova Y70'),
  ('Huawei nova Y90'),
  ('Huawei Mate 50 Pro'),
  ('Huawei Mate 50 Pro Kunlun Glass Edition'),
  ('Huawei Mate 50 RS Porsche Design'),
  ('Huawei Mate 50E'),
  ('Huawei nova 10'),
  ('Huawei nova 10 Pro'),
  ('Huawei nova 10 SE'),
  ('Huawei P60'),
  ('Huawei P60 Pro'),
  ('Huawei P60 Art'),
  ('Huawei Mate X3'),
  ('Huawei Mate 60'),
  ('Huawei Mate 60 Pro'),
  ('Huawei Mate 60 Pro Plus'),
  ('Huawei Mate 60 RS Ultimate'),
  ('Huawei nova 11'),
  ('Huawei nova 11 Pro'),
  ('Huawei nova 11i'),
  ('Huawei nova Y71'),
  ('Huawei nova Y91'),
  ('Huawei Pocket S'),
  ('Huawei Mate X5'),
  ('Huawei nova 12'),
  ('Huawei nova 12 Pro'),
  ('Huawei nova 12 Ultra'),
  ('Huawei nova 12s'),
  ('Huawei nova 12i'),
  ('Huawei nova Y72'),
  ('Huawei Pocket 2'),
  ('Huawei Pura 70'),
  ('Huawei Pura 70 Pro'),
  ('Huawei Pura 70 Ultra'),
  ('Huawei Pura 70 Pro Plus'),
  ('Huawei Mate X6'),
  ('Huawei nova 13'),
  ('Huawei nova 13 Pro'),
  ('Huawei nova 13i'),
  ('Huawei Mate 70'),
  ('Huawei Mate 70 Pro'),
  ('Huawei Mate 70 Pro Plus'),
  ('Huawei Mate 70 RS Ultimate'),
  ('Huawei Mate 70 Air'),
  ('Huawei nova Y63'),
  ('Huawei nova Y73'),
  ('Huawei nova Y72S'),
  ('Huawei Pura 80'),
  ('Huawei Pura 80 Pro'),
  ('Huawei Pura 80 Ultra'),
  ('Huawei Pura X'),
  ('Huawei nova Flip'),
  ('Huawei Mate XT Ultimate Design'),
  ('Huawei Mate X7'),
  ('Huawei Mate 80 Pro'),
  ('Huawei nova 14'),
  ('Huawei nova 14 Pro'),
  ('Honor 9X Pro'),
  ('Honor 9X Lite'),
  ('Honor 30'),
  ('Honor 30 Pro'),
  ('Honor 30 Pro Plus'),
  ('Honor 30S'),
  ('Honor X10'),
  ('Honor X10 Max'),
  ('Honor 10X Lite'),
  ('Honor Play4T'),
  ('Honor Play4T Pro'),
  ('Honor Play 9A'),
  ('Honor V40'),
  ('Honor 50 Pro'),
  ('Honor 50 SE'),
  ('Honor X20'),
  ('Honor X20 SE'),
  ('Honor X30'),
  ('Honor X30i'),
  ('Honor X30 Max'),
  ('Honor 60'),
  ('Honor 60 Pro'),
  ('Honor 60 SE'),
  ('Honor Magic 3'),
  ('Honor Magic 3 Pro'),
  ('Honor Magic 3 Pro Plus'),
  ('Honor Play 5'),
  ('Honor Play 5T Pro'),
  ('Honor Play 30'),
  ('Honor Play 30 Plus'),
  ('Honor Magic 4'),
  ('Honor Magic 4 Pro'),
  ('Honor Magic 4 Ultimate'),
  ('Honor Magic V'),
  ('Honor 70 Pro'),
  ('Honor 70 Pro Plus'),
  ('Honor X7'),
  ('Honor X40i'),
  ('Honor X8 5G'),
  ('Honor X9 5G'),
  ('Honor X40 GT'),
  ('Honor Play 6T'),
  ('Honor Play 6T Pro'),
  ('Honor Play 6C'),
  ('Honor Play 40 Plus'),
  ('Honor 80'),
  ('Honor 80 Pro'),
  ('Honor 80 SE'),
  ('Honor Magic 5'),
  ('Honor Magic 5 Pro'),
  ('Honor Magic 5 Lite'),
  ('Honor Magic Vs'),
  ('Honor Magic Vs Ultimate'),
  ('Honor X5'),
  ('Honor X6'),
  ('Honor X7a'),
  ('Honor X8a'),
  ('Honor X9a'),
  ('Honor X50'),
  ('Honor X50i'),
  ('Honor X6a'),
  ('Honor 90 Lite'),
  ('Honor 90 Pro'),
  ('Honor 100'),
  ('Honor 100 Pro'),
  ('Honor Magic Vs2'),
  ('Honor Play 7T'),
  ('Honor Play 7T Pro'),
  ('Honor Play 50 Plus'),
  ('Honor Magic 6'),
  ('Honor Magic 6 Pro'),
  ('Honor Magic V2'),
  ('Honor Magic V2 RSR Porsche Design'),
  ('Honor X7b'),
  ('Honor X8b'),
  ('Honor X9b'),
  ('Honor X50 Pro'),
  ('Honor X50 GT'),
  ('Honor X50i Plus'),
  ('Honor 200'),
  ('Honor 200 Pro'),
  ('Honor 200 Lite'),
  ('Honor 90 GT'),
  ('Honor Play 8T'),
  ('Honor 300'),
  ('Honor 300 Pro'),
  ('Honor 300 Ultra'),
  ('Honor X5b'),
  ('Honor X5b Plus'),
  ('Honor X6b'),
  ('Honor X7b 5G'),
  ('Honor Magic 7'),
  ('Honor Magic 7 Pro'),
  ('Honor Magic V3'),
  ('Honor Power'),
  ('Honor GT Pro'),
  ('Honor Play 9T'),
  ('Honor Play 9C'),
  ('Honor X70i'),
  ('Honor X9c'),
  ('Honor X9c Smart 5G'),
  ('Honor X6c'),
  ('Honor X7c'),
  ('Honor X7d'),
  ('Honor X9d'),
  ('Honor 400'),
  ('Honor 400 Pro'),
  ('Honor 400 Lite'),
  ('Honor Magic V5'),
  ('Honor Play 60'),
  ('Honor 600'),
  ('Honor 600 Pro'),
  ('Honor 600 Lite'),
  ('Honor Magic 8 Pro'),
  ('Honor X5c Plus'),
  ('Honor X5d'),
  ('Honor Play 80'),
  ('Honor Play 80 Pro'),
  ('Honor Play 10')
on conflict (model_name) do nothing;
