-- เพิ่มรุ่นมือถือยี่ห้อใหม่เข้า device_models (OnePlus, Motorola, Sony, Meizu, LG, HTC, BlackBerry, ZTE/Nubia, Alcatel/TCL, Coolpad)
-- ต่อเนื่องจาก MIGRATION_seed_common_device_models.sql เดิม (idempotent, ไม่ซ้ำ ไม่ลบของเดิม)
insert into public.device_models (model_name)
values
  ('OnePlus 12'),
  ('OnePlus 12R'),
  ('OnePlus 11'),
  ('OnePlus 11R'),
  ('OnePlus 10 Pro'),
  ('OnePlus 10T'),
  ('OnePlus 10R'),
  ('OnePlus 9'),
  ('OnePlus 9 Pro'),
  ('OnePlus 9R'),
  ('OnePlus 9RT'),
  ('OnePlus 8'),
  ('OnePlus 8 Pro'),
  ('OnePlus 8T'),
  ('OnePlus 7'),
  ('OnePlus 7 Pro'),
  ('OnePlus 7T'),
  ('OnePlus 7T Pro'),
  ('OnePlus 6'),
  ('OnePlus 6T'),
  ('OnePlus 5'),
  ('OnePlus 5T'),
  ('OnePlus Nord'),
  ('OnePlus Nord 2'),
  ('OnePlus Nord 3'),
  ('OnePlus Nord CE'),
  ('OnePlus Nord CE 2'),
  ('OnePlus Nord CE 3'),
  ('OnePlus Nord N10'),
  ('OnePlus Nord N100'),
  ('Moto G Power'),
  ('Moto G Play'),
  ('Moto G Stylus'),
  ('Moto G84'),
  ('Moto G73'),
  ('Moto G82'),
  ('Moto G72'),
  ('Moto G62'),
  ('Moto G52'),
  ('Moto G42'),
  ('Moto G32'),
  ('Moto G22'),
  ('Moto G9'),
  ('Moto G8'),
  ('Moto G7'),
  ('Moto G6'),
  ('Moto G5'),
  ('Moto E13'),
  ('Moto E22'),
  ('Moto E32'),
  ('Moto E7'),
  ('Moto E6'),
  ('Moto E5'),
  ('Moto Edge 40'),
  ('Moto Edge 30'),
  ('Moto Edge 20'),
  ('Moto Edge+'),
  ('Moto X4'),
  ('Moto Z3'),
  ('Moto One'),
  ('Sony Xperia 1 V'),
  ('Sony Xperia 1 IV'),
  ('Sony Xperia 1 III'),
  ('Sony Xperia 5 V'),
  ('Sony Xperia 5 IV'),
  ('Sony Xperia 5 III'),
  ('Sony Xperia 10 V'),
  ('Sony Xperia 10 IV'),
  ('Sony Xperia 10 III'),
  ('Sony Xperia XZ3'),
  ('Sony Xperia XZ2'),
  ('Sony Xperia XZ1'),
  ('Sony Xperia XA2'),
  ('Sony Xperia L4'),
  ('Sony Xperia L3'),
  ('Meizu 20'),
  ('Meizu 18'),
  ('Meizu 17'),
  ('Meizu 16'),
  ('Meizu M6'),
  ('Meizu Note 9'),
  ('Meizu Note 8'),
  ('LG G8'),
  ('LG G7'),
  ('LG G6'),
  ('LG G5'),
  ('LG V60'),
  ('LG V50'),
  ('LG V40'),
  ('LG V30'),
  ('LG K92'),
  ('LG K61'),
  ('LG K51'),
  ('LG K42'),
  ('LG K40'),
  ('LG K30'),
  ('LG K22'),
  ('LG Q92'),
  ('LG Q70'),
  ('LG Q60'),
  ('LG Velvet'),
  ('LG Wing'),
  ('LG Stylo 6'),
  ('LG Stylo 5'),
  ('HTC U12+'),
  ('HTC U11'),
  ('HTC U Ultra'),
  ('HTC Desire 20'),
  ('HTC Desire 19'),
  ('HTC One M9'),
  ('HTC One M8'),
  ('HTC One A9'),
  ('BlackBerry KEY2'),
  ('BlackBerry KEYone'),
  ('BlackBerry Priv'),
  ('BlackBerry Passport'),
  ('ZTE Axon 40'),
  ('ZTE Axon 30'),
  ('ZTE Blade A72'),
  ('ZTE Blade A52'),
  ('ZTE Blade V40'),
  ('ZTE Blade V30'),
  ('Nubia Red Magic 8'),
  ('Nubia Red Magic 7'),
  ('TCL 30'),
  ('TCL 20'),
  ('Alcatel 1SE'),
  ('Alcatel 3X'),
  ('Alcatel 1B'),
  ('Coolpad Cool 5'),
  ('Coolpad Note 5')
on conflict (model_name) do nothing;
